name: dart_vlc
description: Flutter media playback, broadcast, recording & chromecast library. Based on libvlc.
version: 0.2.0
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  path: ">=1.8.0 <2.0.0"
  path_provider: ">=2.0.2 <3.0.0"
  audio_video_progress_bar: ^2.0.3
  flutter_native_view: ^0.0.1+1
  window_manager: ^0.3.8

flutter:
  # No platform channel implementation after migration to FFI.
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
      macos:
        pluginClass: DartVlcPlugin
      ios:
        pluginClass: DartVlcPlugin
